export enum RankEnum {
    turai = 'טוראי',
    rabat = 'רב"ט',
    samal= 'סמל',
    samar='סמ"ר',
    rasal= 'רס"ל',
    rasar='רס"ר',
    rasam='רס"ם',
    rasab='רס"ב',
    ranam= 'רנ"ם',
    ranag= 'רנ"ג',
    sagam= 'סג"ם',
    segen= "סגן",
    seren= "סרן",
    rasan= 'רס"ן',
    saal='סא"ל',
    alam= 'סא"ל',
    taal= 'תא"ל',
    aluf="אלוף",
    raal= 'רא"ל', 
  }
 